package com.remitro.event.common.metadata;

public enum EventType {

	// MEMBER
	MEMBER_CREATED,

	MEMBER_LOCKED,
	MEMBER_UNLOCKED_BY_ADMIN,
	MEMBER_UNLOCKED_BY_SELF_VERIFICATION,

	MEMBER_DORMANT,
	MEMBER_ACTIVATED,

	MEMBER_KYC_REQUESTED,
	MEMBER_KYC_VERIFIED,
	MEMBER_KYC_REJECTED,

	MEMBER_ROLE_CHANGED
}
