package com.remitro.member.domain.event;

public enum EventType {

	MEMBER_CREATED,
	MEMBER_ACTIVITY_STATUS_UPDATED,

	MEMBER_KYC_REQUESTED,
	MEMBER_KYC_VERIFIED,
	MEMBER_KYC_REJECTED,

	MEMBER_ROLE_GRANTED,
	MEMBER_ROLE_REVOKED
}
