package com.remitro.account.domain.event;

public enum EventType {

	ACCOUNT_CREATED,
	ACCOUNT_BALANCE_UPDATED,
	ACCOUNT_STATUS_UPDATED,
	ACCOUNT_DEPOSIT,
	ACCOUNT_WITHDRAW,
	ACCOUNT_TRANSFER,
	ACCOUNT_CLOSED
}
