spring:
  application:
    name: transaction-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: remitro.transaction.group

server:
  port: 8083

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
