spring:
  application:
    name: transaction-service

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      retry-count: 2
      retry-interval: 100

server:
  port: 8083

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
