spring:
  application:
    name: api-gateway

server:
  port: 8080      # API ????? ??

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/   # ??? ??? ??

  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://remitro-member                  # ???? ??? ??? ID
          predicates:
            - Path=/api/member/**                   # '/api/member'? ???? ??? ?? ???? ???
        - id: account-service
          uri: lb://remitro-account
          predicates:
            - Path=/api/account/**
        - id: transaction-service
          uri: lb://remitro-transaction
          predicates:
            - Path=/api/transaction/**
